hpc <- read.table("household_power_consumption.txt",sep = ";",skip = 66637,nrows = (69518-66638))
names(hpc) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
hpc$Date <- as.Date(hpc$Date,format = "%d/%m/%Y")
dt <- paste(hpc$Date,hpc$Time)
dtf <- strptime(dt,format="%Y-%m-%d %H:%M:%S")
png(filename = "plot4.png",width = 480, height = 480)
par(mfrow=c(2,2))
plot(dtf,hpc$Global_active_power,type="l",xlab = "",ylab = "Global Active Power(kilowatts)",cex.lab=0.7)
plot(dtf,hpc$Voltage,type="l",xlab = "",ylab = "Voltage",cex.lab=0.7)
plot(dtf,hpc$Sub_metering_1,type="l",xlab = "",ylab = "Energy sub metering",cex.lab=0.7)
lines(dtf,hpc$Sub_metering_2,col="red")
lines(dtf,hpc$Sub_metering_3,col="blue")
legend("topright",pch=c(16,16,16),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex = 0.5)
plot(dtf,hpc$Global_reactive_power,type="l",xlab = "",ylab = "Global reactive power",cex.lab=0.7)
dev.off()